### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by johnflavin** [AdamQBauer/OIS#3]
After I fixed the `normr` issue (see pull request #2) I encountered the following error in running `OISQC`:

``` matlab
Undefined function or variable 'datacondition'.

Error in logmean (line 56)
    [data Sin Sout]=datacondition(data,1);

Error in OISQC (line 102)
        fdata=abs(fft(logmean(mdata),[],2));
```

Not sure if this is from a toolbox or if this is some of your code you've forgotten to check in.

**Comment by AdamQBauer** [comment]
I forgot that one. Should be up now

**Comment by johnflavin** [comment]
Thanks. That led to other missing functions for which I need you to check in the source files.
- `regcorr` — I have a version of this, but you should check in yours in case my version is out of date.
- `normCol` — Same as above.
- `overlaymouse` — I don't have any version of this

**Comment by AdamQBauer** [comment]
Added all
